project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
  resources:
    - img

website:
  title: "Elí Gonzalez"
  search: false
  navbar:
    background: light
    right:
      - href: index.qmd#projects
        text: Projects
      - href: about.qmd
        text: About
      - href: https://medium.com/@eligoze75
        text: Blog
        target: _blank

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    anchor-sections: false
